name: "Build iOS app"

on:
  push:
    branches: [ "main" ]

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - name: ⌘ check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build and Test
        run: xcodebuild clean build test -project CampusCompass.xcodeproj -scheme CampusCompass CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
