name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test CampusCompass
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: latest-stable
      - name: Build and Test
        run: |
          xcodebuild clean build test -project CampusCompass.xcodeproj \
          -destination platform=iOS\ Simulator,OS=16.4,name=iPhone\ 14\ Pro \
          -scheme CampusCompass CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          