name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14 Pro'
          os: 'iOS'
      - name: Run tests
        run: xcodebuild clean test -project "CampusCompass.xcodeproj" -scheme "CampusCompass" -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=latest"
      - name: Build App
        run: xcodebuild -project "CampusCompass.xcodeproj" -scheme "CampusCompass" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
